spring.datasource.url=${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.port=8081

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8090/realms/lilfac/protocol/openid-connect/certs

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

logging.file.name=C:/Users/joser/LilfacWorkspace/Lilfac/logs/lilfac.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n