_format_version: "3.0"

services:
  - name: lilfac-service
    url: http://host.docker.internal:8081
    routes:
      - name: workers-route
        paths:
          - /api/v1/workers
        methods:
          - POST
          - GET
          - PUT
          - DELETE
        strip_path: false

      - name: verification-route
        paths:
          - /api/v1/verification
        methods:
          - POST
          - OPTIONS
        strip_path: false

      - name: parametros-route
        paths:
          - /api/v1/parametros
        methods:
          - GET
          - OPTIONS
        strip_path: false
